# Generated by Django 5.2.11 on 2026-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_metricevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('consent_given', 'Consent given'), ('consent_withdrawn', 'Consent withdrawn'), ('optional_consent_given', 'Optional consent given'), ('optional_consent_withdrawn', 'Optional consent withdrawn'), ('deletion_requested', 'Deletion requested'), ('deletion_processed', 'Deletion processed'), ('session_started', 'Session started'), ('session_completed', 'Session completed'), ('session_abandoned', 'Session abandoned'), ('mock_session_started', 'Mock session started'), ('dataset_export_run', 'Dataset export run'), ('profile_completed', 'Profile completed'), ('withdrawal', 'Withdrawal')], max_length=30),
        ),
    ]
