# Generated by Django 5.2.11 on 2026-02-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('challenges_attempted', models.IntegerField(default=0)),
                ('distraction_free', models.CharField(blank=True, choices=[('yes', 'Yes'), ('mostly', 'Mostly'), ('no', 'No')], max_length=10)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('phone', 'Phone')], max_length=10)),
                ('pyodide_load_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('editor_ready', models.BooleanField(default=False)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_sessions', to='accounts.participant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSessionChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_challenges', to='challenges.challenge')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_challenges', to='coding_sessions.codesession')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('session', 'challenge')},
            },
        ),
        migrations.AddField(
            model_name='codesession',
            name='challenges',
            field=models.ManyToManyField(related_name='code_sessions', through='coding_sessions.CodeSessionChallenge', to='challenges.challenge'),
        ),
        migrations.AddIndex(
            model_name='codesession',
            index=models.Index(fields=['participant', 'status'], name='coding_sess_partici_9bc702_idx'),
        ),
        migrations.AddConstraint(
            model_name='codesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'completed')), models.Q(('status', 'completed'), _negated=True), _connector='OR'), name='completed_status_requires_completed_at'),
        ),
        migrations.AddConstraint(
            model_name='codesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('abandoned_at__isnull', False), ('status', 'abandoned')), models.Q(('status', 'abandoned'), _negated=True), _connector='OR'), name='abandoned_status_requires_abandoned_at'),
        ),
    ]
