# Generated by Django 5.2.11 on 2026-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='is_mock',
            field=models.BooleanField(default=False),
        ),
    ]
