# Generated by Django 6.0.2 on 2026-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding_sessions', '0002_codesession_is_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesession',
            name='wants_harder',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
