# Generated by Django 5.2.11 on 2026-02-14 18:30

import django.db.models.deletion
import simple_history.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalChallenge',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Versioned identifier, e.g. exercism-two-fer-v1', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skeleton_code', models.TextField(blank=True)),
                ('test_cases', models.JSONField(default=list)),
                ('test_cases_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('difficulty', models.IntegerField(help_text='Tier 1-5')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical challenge',
                'verbose_name_plural': 'historical challenges',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='Versioned identifier, e.g. exercism-two-fer-v1', max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('skeleton_code', models.TextField(blank=True)),
                ('test_cases', models.JSONField(default=list)),
                ('test_cases_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('difficulty', models.IntegerField(help_text='Tier 1-5')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['difficulty'], name='challenges__difficu_daa6f9_idx'), models.Index(fields=['is_active'], name='challenges__is_acti_c3aeea_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('difficulty__gte', 1), ('difficulty__lte', 5)), name='challenge_difficulty_range')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('submitted_code', models.TextField(blank=True)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_total', models.IntegerField(default=0)),
                ('time_taken_seconds', models.FloatField(default=0)),
                ('active_time_seconds', models.FloatField(default=0)),
                ('idle_time_seconds', models.FloatField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('think_aloud_active', models.BooleanField(default=False)),
                ('technical_issues', models.BooleanField(default=False)),
                ('paste_count', models.IntegerField(default=0)),
                ('paste_total_chars', models.IntegerField(default=0)),
                ('keystroke_count', models.IntegerField(default=0)),
                ('tab_blur_count', models.IntegerField(default=0)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='challenges.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='accounts.participant')),
            ],
        ),
    ]
