# Generated by Django 5.2.11 on 2026-02-14 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('coding_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='coding_sessions.codesession'),
        ),
        migrations.AddField(
            model_name='historicalchallenge',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['participant'], name='challenges__partici_400592_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeattempt',
            index=models.Index(fields=['session'], name='challenges__session_13681c_idx'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('tests_passed__lte', models.F('tests_total'))), name='tests_passed_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('time_taken_seconds__gte', 0)), name='time_taken_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('active_time_seconds__gte', 0)), name='active_time_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('idle_time_seconds__gte', 0)), name='idle_time_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('tests_passed__gte', 0)), name='tests_passed_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('paste_count__gte', 0)), name='paste_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('keystroke_count__gte', 0)), name='keystroke_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.CheckConstraint(condition=models.Q(('tab_blur_count__gte', 0)), name='tab_blur_count_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeattempt',
            unique_together={('session', 'challenge')},
        ),
    ]
