# Generated by Django 5.2.11 on 2026-02-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='source',
            field=models.JSONField(blank=True, default=dict, help_text='Attribution: dataset name, paper citation, license, URL.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Analysis metadata: complexity_score, function_name, etc.'),
        ),
        migrations.AddField(
            model_name='historicalchallenge',
            name='source',
            field=models.JSONField(blank=True, default=dict, help_text='Attribution: dataset name, paper citation, license, URL.'),
        ),
        migrations.AddField(
            model_name='historicalchallenge',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Analysis metadata: complexity_score, function_name, etc.'),
        ),
    ]
