# Generated by Django 5.2.11 on 2026-03-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_source_challenge_source_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='clarification',
            field=models.TextField(blank=True, default='', help_text='AI-generated parameter docs and worked examples. Additive only – never replaces description.'),
        ),
        migrations.AddField(
            model_name='historicalchallenge',
            name='clarification',
            field=models.TextField(blank=True, default='', help_text='AI-generated parameter docs and worked examples. Additive only – never replaces description.'),
        ),
    ]
