# Generated by Django 5.2.11 on 2026-03-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_add_challengereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='run_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the participant ran the code before final submission.'),
        ),
    ]
