# Generated by Django 6.0.2 on 2026-05-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_widen_difficulty_range_to_include_zero'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='data_quality_flag',
            field=models.CharField(blank=True, default='', help_text="Non-empty when this attempt's accuracy data is unreliable and should be excluded from analysis. Value is a DEV-xxx deviation log ID (see fixtures/DEVIATIONS.md).", max_length=50),
        ),
    ]
