# Generated by Django 5.2.11 on 2026-02-14 18:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
        ('coding_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('scale', 'Scale')], max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choices for single_choice, multi_choice, or scale questions.')),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('min_label', models.CharField(blank=True, max_length=100)),
                ('max_label', models.CharField(blank=True, max_length=100)),
                ('mid_label', models.CharField(blank=True, max_length=100)),
                ('context', models.CharField(choices=[('profile', 'Profile'), ('post_challenge', 'Post-challenge'), ('post_session', 'Post-session')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['context', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalSurveyQuestion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('text', models.TextField()),
                ('help_text', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('scale', 'Scale')], max_length=20)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choices for single_choice, multi_choice, or scale questions.')),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
                ('min_label', models.CharField(blank=True, max_length=100)),
                ('max_label', models.CharField(blank=True, max_length=100)),
                ('mid_label', models.CharField(blank=True, max_length=100)),
                ('context', models.CharField(choices=[('profile', 'Profile'), ('post_challenge', 'Post-challenge'), ('post_session', 'Post-session')], max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical survey question',
                'verbose_name_plural': 'historical survey questions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('challenge_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='challenges.challengeattempt')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='accounts.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.surveyquestion')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='coding_sessions.codesession')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='surveys.surveyresponse')),
            ],
            options={
                'indexes': [models.Index(fields=['participant', 'question'], name='surveys_sur_partici_8ae45b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('challenge_attempt__isnull', True), ('session__isnull', True)), models.Q(('challenge_attempt__isnull', True), ('session__isnull', False)), models.Q(('challenge_attempt__isnull', False), ('session__isnull', True)), _connector='OR'), name='survey_response_fk_exclusivity')],
            },
        ),
    ]
