# Generated by Django 5.2.11 on 2026-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveyquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='Choices for single/multi_choice or scale.'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='Choices for single/multi_choice or scale.'),
        ),
    ]
