# Generated by Django 5.2.11 on 2026-02-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_alter_historicalsurveyquestion_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveyquestion',
            name='context',
            field=models.CharField(choices=[('profile', 'Profile'), ('post_challenge', 'Post-challenge'), ('post_session', 'Post-session'), ('exit', 'Exit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='context',
            field=models.CharField(choices=[('profile', 'Profile'), ('post_challenge', 'Post-challenge'), ('post_session', 'Post-session'), ('exit', 'Exit')], max_length=20),
        ),
    ]
