# Generated by Django 6.0.2 on 2026-05-04 17:33

from django.db import migrations


def remove_education_question(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")
    SurveyQuestion.objects.filter(text="What is your highest level of education?").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_historicalsurveyquestion_context_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_education_question, migrations.RunPython.noop),
    ]
