# Generated by Django 6.0.2 on 2026-05-04 17:34

from django.db import migrations


def update_questions(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")
    questions = SurveyQuestion.objects.filter(
        text__in=[
            "How many years of programming experience do you have?",
            "How many years have you been writing Python specifically?",
        ]
    )
    for q in questions:
        q.question_type = "number"
        q.choices = []
        q.save()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_remove_education_question'),
    ]

    operations = [
        migrations.RunPython(update_questions, reverse_code=migrations.RunPython.noop),
    ]
