# Generated by Django 6.0.2 on 2026-05-04 17:36

from django.db import migrations


def update_stem_question(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")
    SurveyQuestion.objects.filter(
        text="Is your educational background in computer science or a related field?"
    ).update(
        text="Is your educational background in computer science or a related field? (STEM: Science, Technology, Engineering, and Mathematics)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_update_experience_questions_to_number'),
    ]

    operations = [
        migrations.RunPython(update_stem_question),
    ]
