# Generated by Django 6.0.2 on 2026-05-04 17:38

from django.db import migrations

def update_experience_questions(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")

    questions_to_update = [
        "How many years of programming experience do you have?",
        "How many years have you been writing Python specifically?",
    ]

    SurveyQuestion.objects.filter(text__in=questions_to_update).update(
        scale_min=0,
        scale_max=60
    )

def reverse_update(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")

    questions_to_update = [
        "How many years of programming experience do you have?",
        "How many years have you been writing Python specifically?",
    ]

    SurveyQuestion.objects.filter(text__in=questions_to_update).update(
        scale_min=None,
        scale_max=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_update_stem_question_text'),
    ]

    operations = [
        migrations.RunPython(update_experience_questions, reverse_update),
    ]
