# Generated by Django 6.0.2 on 2026-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_add_min_max_to_experience_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsurveyquestion',
            name='scale_max',
            field=models.IntegerField(blank=True, help_text='Max value (for scale or number).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalsurveyquestion',
            name='scale_min',
            field=models.IntegerField(blank=True, help_text='Min value (for scale or number).', null=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='scale_max',
            field=models.IntegerField(blank=True, help_text='Max value (for scale or number).', null=True),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='scale_min',
            field=models.IntegerField(blank=True, help_text='Min value (for scale or number).', null=True),
        ),
    ]
