# Generated by Django 6.0.2 on 2026-05-06 06:10

from django.db import migrations
from django.db.models import Count


def remove_duplicate_survey_questions(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")
    SurveyResponse = apps.get_model("surveys", "SurveyResponse")

    duplicates = (
        SurveyQuestion.objects.values("text", "context")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        questions = SurveyQuestion.objects.filter(
            text=dup["text"],
            context=dup["context"]
        ).order_by("id")

        canonical = questions[0]
        for q in questions[1:]:
            SurveyResponse.objects.filter(question=q).update(question=canonical)
            q.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_historicalsurveyquestion_scale_max_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_survey_questions, reverse_code=migrations.RunPython.noop),
    ]
