# Generated by Django 6.0.2 on 2026-05-06 06:10

from django.db import migrations
from django.db.models import Count


def remove_duplicate_survey_questions(apps, schema_editor):
    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")

    # Find duplicates based on text and context
    duplicates = (
        SurveyQuestion.objects.values("text", "context")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for dup in duplicates:
        # Get all instances of this duplicate
        questions = SurveyQuestion.objects.filter(
            text=dup["text"],
            context=dup["context"]
        ).order_by("id")

        # Keep the first one, delete the rest
        to_delete = questions[1:]
        for q in to_delete:
            q.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_historicalsurveyquestion_scale_max_and_more'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_survey_questions, reverse_code=migrations.RunPython.noop),
    ]
