# Generated by Django 5.2.11 on 2026-02-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalconsentrecord',
            name='consent_type',
            field=models.CharField(choices=[('reminder_emails', 'Reminder emails'), ('think_aloud_audio', 'Think-aloud audio'), ('transcript_sharing', 'Transcript sharing'), ('future_contact', 'Future contact for follow-up interview')], max_length=30),
        ),
    ]
