# Generated by Django 6.0.2 on 2026-05-04 16:49

from django.db import migrations


def add_consent_document(apps, schema_editor):
    ConsentDocument = apps.get_model("consent", "ConsentDocument")

    title = "Participant Information Sheet and Consent Form"
    body = """
<h2 class="title is-4">Participant Information Sheet and Consent Form</h2>
<p><strong>Royal Holloway, University of London</p>

<p><strong>Project Title:</strong> Longitudinal Assessment of the Relationship Between AI-Assisted Coding Practices and Python Coding Skill</p>
<p><strong>Principal Investigator’s name and email address:</strong> Dr Andy Woods, <a href="mailto:andy.woods@rhul.ac.uk">andy.woods@rhul.ac.uk</a></p>

<p>You are being invited to take part in a research project. Before you decide to consent to take part it is important for you to understand why the research is taking place and what your participation will involve. Please take time to read the following information carefully and discuss it with others if you wish. Ask us if there is anything that is not clear or if you would like more information. Please consider carefully whether you wish to consent to take part.</p>

<h3 class="title is-5 mt-5">Why is this research being conducted?</h3>
<p>AI coding assistants (tools that write code for you as you guide and review) have become widely used among software developers. "Vibe coding" (as it is increasingly called) raises an important question: if AI generates most of your code day to day, does your ability to code without it change over time?</p>
<p>This study aims to find out. We are recruiting Python coders across all levels of AI tool use (from none to heavy) to complete periodic Python coding challenges over 12 months. By comparing performance over time with self-reported AI coding habits, we hope to establish whether AI-assisted coding is associated with changes in coding skill.</p>
<p>This is a citizen-science project: the data you contribute will help answer a question that matters to the developer community, and we will share the results and the anonymised dataset openly.</p>

<h3 class="title is-5 mt-5">Why have I been invited to take part?</h3>
<p>You have been invited because you write code in Python. We are recruiting adults (aged 18 or over) with any level of Python experience, from beginners to experts, and from people who never use AI coding tools to those who use them constantly. We aim to recruit at least 200 participants, with no upper limit.</p>
<p>You do not need to use AI coding tools to participate. Your data is still very useful to us.</p>
<p>The study materials, consent process, survey questions, and task instructions are currently provided in English only. You do not need to be a native English speaker to take part, but you should only participate if you are comfortable reading English well enough to understand what the study involves and what your rights are. If anything is unclear, please contact the researcher before deciding whether to participate.</p>

<h3 class="title is-5 mt-5">Do I have to take part?</h3>
<p>No. It is entirely up to you whether you take part. You can choose not to participate without any consequences and without needing to give a reason.</p>
<p>If you decide to take part, you will be asked to give your consent before your first session. You can withdraw from the study at any time and for any reason, simply by using the withdrawal option in your account settings. You can also request that your data be automatically deleted within moments at any time before the dataset is anonymised. After anonymisation, it will no longer be possible to identify or remove individual data; your data will be anonymised and used only in aggregate form.</p>

<h3 class="title is-5 mt-5">What will my participation involve?</h3>
<h4 class="title is-6">Overview</h4>
<p>You will create an account on our platform (canistillcode.org) and complete periodic coding sessions, roughly once a month, at a time that suits you.</p>
<p>Each session:</p>
<ol>
    <li>You will be given short Python coding challenges, shown one at a time. Each challenge involves completing a partially written Python function. You can complete as many or as few as you like, up to a maximum of 10 challenges.</li>
    <li>Your code runs directly in your browser, nothing is installed, and your code is not sent to a server.</li>
    <li>After each challenge, you will answer brief reflection questions (e.g., "Did this feel harder than usual?").</li>
    <li>You choose how many challenges to complete (from 1 to 10). You can stop at any time.</li>
    <li>After your last challenge for the session, you will complete a short survey (approximately 2–3 minutes) about your current coding habits. Including, if applicable, how much of your coding time is AI-assisted.</li>
</ol>
<p><strong>Session duration:</strong> Typically 5–25 minutes depending on how many challenges you complete.</p>
<p><strong>Session frequency:</strong> Minimum 28 days between sessions. No maximum gap, you can return after a month or after 11 months.</p>
<p>Before each session, you will see a brief reminder to work without AI assistance (no Copilot, no ChatGPT, no Googling) and to do so in a quiet environment if possible. This is so your performance reflects your own unassisted coding ability. You will be asked to confirm you have read this reminder.</p>
<p>At study exit (or after 12 months): You will be invited to complete a short exit survey with optional open-ended questions about your experience of any skill changes and how you attribute them. There are no right or wrong answers.</p>
<p><strong>Optional follow-up interview:</strong> At the end of the exit survey, you will be asked whether you would be willing to be contacted about a possible follow-up interview (by video call, approximately 45–60 minutes). This is entirely optional. If you agree, your account email will be used to contact you; you can decline or withdraw your interest at any time.</p>

<h3 class="title is-5 mt-5">Will I be contacted during the study?</h3>
<p>We will send you a brief reminder email approximately once per month to let you know a new session is available. These emails will contain only a link to the platform and a short prompt. No personal data about your performance will be included in the email itself.</p>
<p>You can opt out of reminder emails at any time via your account settings. Opting out of reminders does not affect your participation. You can continue completing sessions without them.</p>
<p>We will not contact you for any other purpose during the study without your explicit consent, except to notify you of any significant changes to the study that may affect your participation.</p>

<h3 class="title is-5 mt-5">What are the possible disadvantages and risks in taking part, and how might these be mitigated?</h3>
<p>The risks are minimal. The coding challenges involve cognitive effort and can be mildly frustrating; they are comparable to everyday coding tasks and well within the range of normal professional activity. You are explicitly told before each session that this is not a test you can fail; the goal is to track consistent patterns over time, not to judge your performance on any given day.</p>
<p>You may skip any individual challenge or stop your session at any point without consequence or explanation.</p>
<p>Your email address is the only personally identifiable data we hold. It is used solely for account authentication and, if you opt in, for session reminder emails. It is stored securely on EU-based servers and is never shared with third parties. It is removed from the dataset before any data is shared with other researchers or released publicly.</p>
<p>Although we take all reasonable precautions to protect your data, it is important to note that, as with any online system, no data storage can be guaranteed to be completely free from the risk of a breach. Please contact us at <a href="mailto:andy.woods@rhul.ac.uk">andy.woods@rhul.ac.uk</a> if you have any concerns.</p>

<h3 class="title is-5 mt-5">Are there any benefits in taking part?</h3>
<p>Yes. As a participant, you will:</p>
<ol>
    <li>Have access to a personalised dashboard showing your performance trends over time.</li>
    <li>Contribute to the first large-scale longitudinal dataset on AI coding practices and skill. This question directly affects the developer community you are part of.</li>
    <li>Have the opportunity to see the open dataset and published findings once released.</li>
</ol>
<p>There is no financial payment for taking part.</p>

<h3 class="title is-5 mt-5">What information about me will be collected and why is the collection of this information relevant for achieving the research objectives?</h3>
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th>Data Category</th>
            <th>Purpose and Identifiability</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Email address</td>
            <td>Account login and optional reminders | Identifiable; stored separately from research data</td>
        </tr>
        <tr>
            <td>Profile survey responses (Python experience, role, AI tools used, etc.)</td>
            <td>Baseline covariates for analysis | Pseudonymous (participant ID only)</td>
        </tr>
        <tr>
            <td>Coding challenge performance (accuracy, active time)</td>
            <td>Primary research outcome | Pseudonymous</td>
        </tr>
        <tr>
            <td>Post-session survey responses (AI coding habits, hours per week)</td>
            <td>Primary independent variables | Pseudonymous</td>
        </tr>
        <tr>
            <td>Exit survey free-text responses</td>
            <td>Qualitative strand | Pseudonymous; reviewed before release</td>
        </tr>
        <tr>
            <td>Optional: interview recording and transcript</td>
            <td>Qualitative strand | Identifiable during processing; recordings deleted after transcription; transcripts pseudonymised</td>
        </tr>
    </tbody>
</table>

<p><strong>Storage:</strong> All data is stored on EU-based servers (Hetzner, Germany) in compliance with UK GDPR. The researcher (Andy Woods) and authorised members of the research team at Royal Holloway will have access to the data.</p>

<p><strong>Retention:</strong> Identifiable account data, including email addresses, will be deleted automatically within moments if you withdraw from the study before the dataset is anonymised. If you do not withdraw, these data will be deleted 12 months after you started the study. Pseudonymous research data is retained for 10 years after publication, in line with Royal Holloway data retention policy.</p>

<p><strong>Data sharing:</strong> A fully anonymised version of the dataset will be released publicly after a 12-month embargo from the date of first data collection. Free-text responses will be reviewed for identifiability before release. Interview transcripts will never be included in the public dataset.</p>

<p><strong>Re-use:</strong> The anonymised dataset may be used by Royal Holloway researchers and deposited in open data archives. Results may be used in academic publications, conference presentations, and other research outputs.</p>

<h3 class="title is-5 mt-5">How will the results of my participation be used? Will the research be published? Could I be identified from any publications or other research outputs?</h3>
<p>The findings from the research will/may be written up for academic publications, conference presentations, a report commissioned by an external organisation, websites, videos etc. Participants will not be identifiable from the outputs.</p>
<p>We would like your permission to use direct quotations [and for your name to be attributed to these/ but without identifying you] in any research outputs.</p>

<h3 class="title is-5 mt-5">Who do I contact if I have a concern about the research or I wish to complain?</h3>
<p>If you have a concern about any aspect of this study, please contact the primary researcher, Andy Woods, via <a href="mailto:andy.woods@rhul.ac.uk">andy.woods@rhul.ac.uk</a>, or Royal Holloway’s Research Ethics Committee via <a href="mailto:ethics@rhul.ac.uk">ethics@rhul.ac.uk</a>. If you wish to make a formal complaint, please email <a href="mailto:integrity@rhul.ac.uk">integrity@rhul.ac.uk</a>.</p>

<h3 class="title is-5 mt-5">Ethical Approval</h3>
<p>This study has received ethics approval from Royal Holloway, University of London’s Research Ethics Committee, with the approval ID of 991.</p>

<h3 class="title is-5 mt-5">Safeguarding and when confidentiality may need to be breached</h3>
<p>All information you provide during this study will be treated as confidential and handled in accordance with UK GDPR and Royal Holloway's data protection policies.</p>
<p>This study does not involve clinical care, therapeutic relationships, or work with vulnerable populations. Participants are adult members of the public (aged 18+) completing voluntary coding challenges. Accordingly, there are no foreseeable circumstances in which confidentiality would need to be breached.</p>

<h3 class="title is-5 mt-5">Data protection</h3>
<p>This research commits to abide by the Data Protection Act (2018).</p>

<h3 class="title is-5 mt-5">General Data Protection Regulation Statement</h3>
<p>Important General Data Protection Regulation information (GDPR). Royal Holloway, University of London is the sponsor for this study and is based in the UK. We will be using information from you in order to undertake this study and will act as the data controller for this study. This means that we are responsible for looking after your information and using it properly. Any data you provide during the completion of the study will be stored securely on hosted on servers within the European Economic Area’. Royal Holloway is designated as a public authority and in accordance with the Royal Holloway and Bedford New College Act 1985 and the Statutes which govern the College, we conduct research for the public benefit and in the public interest. Royal Holloway has put in place appropriate technical and organisational security measures to prevent your personal data from being accidentally lost, used or accessed in any unauthorised way or altered or disclosed. Royal Holloway has also put in place procedures to deal with any suspected personal data security breach and will notify you and any applicable regulator of a suspected breach where legally required to do so. To safeguard your rights, we will use the minimum personally-identifiable information possible (i.e., the email address you provide us). The lead researcher will keep your contact details confidential and will use this information only as required (i.e., to provide a summary of the study results if requested and/or for the prize draw). The lead researcher will keep information about you and data gathered from the study, the duration of which will depend on the study. Certain individuals from RHUL may look at your research records to check the accuracy of the research study. If the study is published in a relevant peer-reviewed journal, the anonymised data may be made available to third parties. The people who analyse the information will not be able to identify you. You can find out more about your rights under the GDPR and Data Protection Act 2018 by visiting <a href="https://www.royalholloway.ac.uk/about-us/more/governance-and-strategy/data-protection/">https://www.royalholloway.ac.uk/about-us/more/governance-and-strategy/data-protection/</a> and if you wish to exercise your rights, please contact <a href="mailto:dataprotection@royalholloway.ac.uk">dataprotection@royalholloway.ac.uk</a></p>

<p class="mt-5">NB: You may retain this information sheet for reference and contact us with any queries.</p>

<hr>

<h2 class="title is-4 mt-6">Participant Consent Form</h2>
<p><strong>Name and email address of researcher:</strong></p>
<p>Lead researcher: Dr Andy Woods — andy.woods@rhul.ac.uk<br>
Co-Investigator: Dr Alex Reppel — alex.reppel@rhul.ac.uk<br>
PhD Researcher: Chris Chowen — christopher.chowen.2024@live.rhul.ac.uk</p>

<p>Please read the following statements and indicate your response by clicking the ‘I consent’ button.</p>

<ul class="mt-4 mb-4" style="list-style-type: disc; margin-left: 1.5rem;">
    <li>I confirm that I have read and understood the information sheet about this study</li>
    <li>I agree to participate in this study</li>
    <li>I have had the opportunity to ask questions about this study</li>
    <li>I have received satisfactory answers to my questions about this study</li>
    <li>I understand my participation in this study is voluntary</li>
    <li>I understand that I am free to withdraw from the study/research project at any time without giving a reason and without detriment to myself</li>
    <li>I understand that I may request the automatic deletion of my data within moments at any time before the dataset is anonymised, by using the withdrawal option in my account settings or by emailing andy.woods@rhul.ac.uk. After anonymisation, individual data can no longer be identified or removed.</li>
    <li>I understand that my email address will be stored securely for account authentication and will not be used for any other purpose without my consent.</li>
    <li>I understand that identifiable account data, including my email address, will be deleted automatically within moments if I withdraw from the study before the dataset is anonymised. If I do not withdraw, these data will be deleted 12 months after I started the study.</li>
    <li>I understand that I will receive periodic session reminder emails (approximately monthly) during my participation (you can change this preference at any time in your account settings).</li>
    <li>I understand that my research data (coding performance and survey responses) will be stored pseudonymously (linked to a participant ID, not my name or email) on EU-based servers.</li>
    <li>I understand that an anonymised version of the dataset may be released publicly after a 12-month embargo, and may be used in academic publications and deposited in open data archives.</li>
    <li>I understand that confidentiality of my anonymised data may be at risk in the event of a data breach, and that while all reasonable precautions are taken, no online system can entirely eliminate this risk.</li>
    <li>I understand that at the end of my participation I will be asked whether I am willing to be contacted for an optional follow-up interview, and that I am free to decline or to withdraw my agreement at any time.</li>
    <li>I confirm that I am sufficiently comfortable reading English to understand the information sheet, what participation involves, and my rights as a participant, and that I have had the opportunity to ask questions before consenting.</li>
</ul>

<p>Please note that this Consent form will be stored separately from the responses you provide.</p>

<p>If you have any concerns about this research, please email <a href="mailto:ethics@rhul.ac.uk">ethics@rhul.ac.uk</a>.</p>
"""

    # We want to make sure this is the active document.
    # Set all other documents to inactive just in case.
    ConsentDocument.objects.all().update(is_active=False)

    ConsentDocument.objects.create(
        version=1,
        title=title,
        body=body,
        is_active=True,
    )


def remove_consent_document(apps, schema_editor):
    ConsentDocument = apps.get_model("consent", "ConsentDocument")
    ConsentDocument.objects.filter(title="Participant Consent Form", version=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('consent', '0003_debrief_record'),
    ]

    operations = [
        migrations.RunPython(add_consent_document, remove_consent_document),
    ]
